In [57]:
from tensorflow.keras.preprocessing.text import one_hot

In [70]:
## Sentences
sent={  'The glass of milk ',
      'The glass of juice ',
      'the cup of tea',
      'i am a good boy',
      'i am a good developer',
      'understand the meaning of words',
      'your video are good',}

In [71]:
sent

{'The glass of juice ',
 'The glass of milk ',
 'i am a good boy',
 'i am a good developer',
 'the cup of tea',
 'understand the meaning of words',
 'your video are good'}

In [72]:
##  Define the vocabulary size 
voc_size=10000

In [73]:
## One hot representation 
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr # These are index of above words .

[[9670, 8079, 2412, 7331, 8979],
 [8180, 2177, 1505, 9716],
 [9670, 8079, 2412, 7331, 1037],
 [8180, 8943, 1505, 2301],
 [6434, 860, 5428, 7331],
 [2911, 8180, 8655, 1505, 4179],
 [8180, 8943, 1505, 3857]]

In [74]:
## Word embedding representation 
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing .sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [75]:
import numpy as np 
sent_length=8
Embedding_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(Embedding_doc)

[[   0    0    0 9670 8079 2412 7331 8979]
 [   0    0    0    0 8180 2177 1505 9716]
 [   0    0    0 9670 8079 2412 7331 1037]
 [   0    0    0    0 8180 8943 1505 2301]
 [   0    0    0    0 6434  860 5428 7331]
 [   0    0    0 2911 8180 8655 1505 4179]
 [   0    0    0    0 8180 8943 1505 3857]]


In [76]:
# Feature representation 
dim=10

In [77]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [78]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [79]:
model.predict(Embedding_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step


array([[[-2.87086014e-02,  2.77404301e-02, -4.17731293e-02,
         -2.66657602e-02, -4.08141240e-02,  2.42043771e-02,
         -1.43037550e-02,  2.20049135e-02, -1.84227228e-02,
         -2.13047396e-02],
        [-2.87086014e-02,  2.77404301e-02, -4.17731293e-02,
         -2.66657602e-02, -4.08141240e-02,  2.42043771e-02,
         -1.43037550e-02,  2.20049135e-02, -1.84227228e-02,
         -2.13047396e-02],
        [-2.87086014e-02,  2.77404301e-02, -4.17731293e-02,
         -2.66657602e-02, -4.08141240e-02,  2.42043771e-02,
         -1.43037550e-02,  2.20049135e-02, -1.84227228e-02,
         -2.13047396e-02],
        [-4.84183431e-02, -2.97784694e-02,  3.63888182e-02,
         -4.42163125e-02,  3.14340256e-02, -2.20184326e-02,
         -4.72282059e-02,  2.25723274e-02, -2.50399113e-04,
          1.21147633e-02],
        [-2.95596961e-02, -5.29292971e-03,  6.90702349e-03,
         -5.63289970e-03,  1.77698247e-02,  3.20201553e-02,
         -4.70652245e-02, -2.40703952e-02, -6.574869

In [80]:
Embedding_doc[0]

array([   0,    0,    0, 9670, 8079, 2412, 7331, 8979])